#ifndef __MCT_VERSION_H_
#define __MCT_VERSION_H_

#define _MCT_PACKAGE_VERSION_STATE "@MCT_VERSION_STATE@"
#define _MCT_PACKAGE_VERSION "@PROJECT_VERSION@"
#define _MCT_PACKAGE_MAJOR_VERSION "@PROJECT_VERSION_MAJOR@"
#define _MCT_PACKAGE_MINOR_VERSION "@PROJECT_VERSION_MINOR@"
#define _MCT_PACKAGE_PATCH_LEVEL "@PROJECT_VERSION_PATCH@"
#define _MCT_PACKAGE_REVISION "@MCT_REVISION@"

#endif
