#ifndef __DLT_VERSION_H_
#define __DLT_VERSION_H_

#define _DLT_PACKAGE_VERSION_STATE "@DLT_VERSION_STATE@"
#define _DLT_PACKAGE_VERSION "@PROJECT_VERSION@"
#define _DLT_PACKAGE_MAJOR_VERSION "@PROJECT_VERSION_MAJOR@"
#define _DLT_PACKAGE_MINOR_VERSION "@PROJECT_VERSION_MINOR@"
#define _DLT_PACKAGE_PATCH_LEVEL "@PROJECT_VERSION_PATCH@"
#define _DLT_PACKAGE_REVISION "@DLT_REVISION@"

#endif
